import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  parentContainer: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  nutriScore: {
    width: 341,
    height: 76,
    backgroundColor: '#a94446',
    marginTop: 15.5,
    alignSelf: 'center',
    flexDirection: 'row',
    borderRadius: 5,
  },
  internalView: {
    flexDirection: 'row',
    elevation: -5,
  },
  headingAndSubHeading: {
    flexDirection: 'column',
  },
  title: {
    fontFamily: 'Merriweather-Bold',
    fontSize: 16,
    lineHeight: 28,
    letterSpacing: -0.24,
    color: '#fff',
    marginLeft: 15,
    marginTop: 12,
  },
  subheading: {
    fontFamily: 'Merriweather-Light',
    fontSize: 12,
    lineHeight: 19,
    letterSpacing: -0.18,
    color: '#fff',
    marginLeft: 15,
  },
  scoreView: {
    width: 84,
    height: 40,
    backgroundColor: '#fff',
    borderRadius: 5,
    marginVertical: 18,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 36,
    flexDirection: 'row',
  },
  scoreText: {
    fontFamily: 'ProximaNova-Bold',
    fontSize: 17,
    lineHeight: 29,
    letterSpacing: -0.26,
    color: '#373334',
  },
  right_arrowImage: {
    width: 5.7,
    height: 9.7,
    marginLeft: 14.5,
  },
  filterFood: {
    flexDirection: 'row',
    marginHorizontal: 15,
    marginTop: 16,
    justifyContent: 'space-between',
  },
  eatingTimes_all: {
    width: 60,
    height: 41,
    borderRadius: 21,
    borderColor: '#dde1e5',
    borderWidth: 1,
  },
  eatingTimes_breakfast: {
    width: 103,
    height: 41,
    borderRadius: 21,
    borderColor: '#dde1e5',
    borderWidth: 1,
  },
  eatingTimes_L_D: {
    width: 80,
    height: 41,
    borderRadius: 21,
    borderColor: '#dde1e5',
    borderWidth: 1,
  },
  textNormal: {
    fontFamily: 'Merriweather-Regular',
    fontSize: 14,
    lineHeight: 20,
    color: '#2f2f2f',
    marginLeft: 15,
    marginTop: 8,
  },
  textActive: {
    fontFamily: 'Merriweather-Bold',
    fontSize: 14,
    lineHeight: 20,
    color: '#2f2f2f',
    marginLeft: 15,
    marginTop: 8,
  },
  activeEatingTimes_all: {
    borderColor: '#191919',
    borderRadius: 21,
    borderWidth: 1,
    width: 60,
    height: 41,
  },
  activeEatingTimes_breakfast: {
    borderColor: '#191919',
    borderRadius: 21,
    borderWidth: 1,
    width: 103,
    height: 41,
  },
  activeEatingTimes_L_D: {
    borderColor: '#191919',
    borderRadius: 21,
    borderWidth: 1,
    width: 80,
    height: 41,
  },
  macroNutrients: {
    width: 298,
    height: 501.3,
    backgroundColor: '#fff',
    elevation: 2,
    marginTop: 23,
    marginHorizontal: 38,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#d5d5d5',
  },
  macroNutrientsTitle: {
    fontFamily: 'Merriweather-Bold',
    fontSize: 16,
    lineHeight: 23,
    letterSpacing: -0.24,
    color: '#373334',
    marginTop: 17,
    marginLeft: 21,
  },
  macroNutrientsSubHeading: {
    fontFamily: 'Merriweather-Light',
    fontSize: 13,
    lineHeight: 22,
    letterSpacing: -0.2,
    color: '#7a7a8f',
    marginLeft: 20,
    marginTop: 10,
  },
  myGoalsTitle: {
    fontFamily: 'Merriweather-Bold',
    fontSize: 16,
    lineHeight: 23,
    letterSpacing: -0.24,
    marginTop: 212,
    color: '#373334',
    marginLeft: 20,
  },
  overlay: {
    width: 268,
    height: 147,
    borderRadius: 9,
    backgroundColor: '#fff',
    borderColor: '#e2e2e2',
    borderWidth: 1,
    marginHorizontal: 15,
    marginTop: 12,
    elevation: 2,
  },
});
