import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  background: {
    width: 343,
    height: 152,
    backgroundColor: '#fff',
    alignSelf: 'center',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#fff',
    marginTop: 35.2,
  },
  aboveLine: {
    height: 109.8,
    flexDirection: 'row',
  },
  belowLine: {
    height: 42.2,
    flexDirection: 'row',
  },
  leftImageColumn: {
    marginTop: 14,
    marginLeft: 11,
    borderRadius: 5,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#fff',
  },
  rightDetailsColumn: {
    marginLeft: 13,
    marginTop: 13,
    marginBottom: 13.8,
    flexDirection: 'column',
  },
  divider: {
    width: 343,
    backgroundColor: '#ececec',
    height: 1,
  },
  foodImage: {
    width: 63,
    height: 63,
  },
  title: {
    fontFamily: 'Merriweather-Regular',
    fontSize: 14,
    color: '#373334',
    lineHeight: 19,
    letterSpacing: -0.21,
    width: 104,
    height: 39,
  },
  belowTitle: {
    flexDirection: 'row',
  },
  roadImage: {
    width: 15.2,
    height: 12.4,
    marginTop: 11,
  },
  roadText: {
    fontFamily: 'Merriweather-Regular',
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: -0.21,
    color: '#383435',
    width: 59,
    height: 18,
    marginLeft: 7.8,
    marginTop: 5,
  },
  pickupText: {
    fontFamily: 'Merriweather-Regular',
    fontSize: 12,
    lineHeight: 20,
    letterSpacing: -0.18,
    color: '#7a7a8f',
    width: 51,
    height: 18,
    marginTop: 6,
  },
  value: {
    marginLeft: 4,
    fontFamily: 'Merriweather-Regular',
    color: '#373334',
    lineHeight: 20,
    letterSpacing: -0.18,
    fontSize: 12,
    marginTop: 6,
  },
  stopwatchImage: {
    width: 10,
    height: 12.6,
    marginLeft: 26.8,
    marginTop: 10,
    marginRight: 7.2,
  },
  deliveryTimeText: {
    fontFamily: 'Merriweather-Regular',
    fontSize: 12,
    lineHeight: 20,
    letterSpacing: -0.18,
    color: '#7a7a8f',
    width: 87,
    height: 18,
    marginTop: 6,
  },
  storeImage: {
    width: 14,
    height: 11,
    marginLeft: 15,
    marginTop: 15,
  },
  restaurantTitle: {
    color: '#7a7a8f',
    marginLeft: 10,
    marginTop: 11.2,
    width: 98,
    fontSize: 12,
    fontFamily: 'Merriweather-Regular',
    lineHeight: 20,
    letterSpacing: -0.18,
    height: 15,
  },
  priceView: {
    width: 49,
    height: 25,
    marginTop: 8.2,
    marginLeft: 146,
    backgroundColor: '#EEEEEE',
    borderRadius: 6,
  },
  priceText: {
    width: 38,
    height: 15,
    fontFamily: 'Merriweather-Regular',
    fontSize: 12,
    lineHeight: 15,
    letterSpacing: -0.18,
    color: 'black',
    marginTop: 4,
    marginLeft: 7,
  },
});
