import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  underlinedText: {
    textDecorationLine: 'underline',
    fontSize: 10,
    marginLeft: 23,
    color: 'white',
  },
  viewDetailsButtonView: {
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    elevation: 2,
    marginBottom: 5,
    height: 30,
    width: 100,
    marginLeft: 12,
  },
  buttonTextForViewDetails: {
    color: 'black',
    fontWeight: 'bold',
    fontStyle: 'italic',
    fontSize: 12,
  },
  facebookIcon: {
    height: 20.2,
    width: 20.2,
    marginRight: 10,
  },
  buttonTextForLogin: {color: 'white', fontWeight: 'bold'},
  loginButtonView: {
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#a94446',
    height: 50,
    alignSelf: 'center',
    flexDirection: 'row',
    width: 296,
    marginBottom: 12,
  },
  buttonTextForFacebookLogin: {
    color: 'black',
    fontWeight: '700',
  },
  facebookLoginButtonView: {
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'white',
    elevation: 2,
    height: 50,
    alignSelf: 'center',
    flexDirection: 'row',
    width: 296,
    marginBottom: 12,
  },
});
