import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  underlinedText: {
    textDecorationLine: 'underline',
    fontSize: 10,
    marginLeft: 30,
    color: 'white',
  },
  viewDetailsButtonView: {
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    elevation: 2,
    marginBottom: 5,
    height: 30,
    width: 93,
    marginLeft: 21,
  },
  buttonTextForViewDetails: {
    color: '#2f2f2f',
    fontFamily: 'Merriweather-BoldItalic',
    fontSize: 12,
  },
  facebookIcon: {
    height: 20.2,
    width: 20.2,
    marginRight: 13,
  },
  buttonTextForLogin: {
    color: 'white',
    fontFamily: 'ProximaNova-Bold',
    fontSize: 16,
    color: '#fff',
    textAlign: 'left',
  },
  loginButtonView: {
    borderRadius: 25,
    alignItems: 'center',
    marginLeft: 18,
    marginRight: 20.2,
    justifyContent: 'center',
    backgroundColor: '#a94446',
    height: 50,
    alignSelf: 'center',
    flexDirection: 'row',
    marginBottom: 13,
    width: 296,
    marginBottom: 12,
  },
  buttonTextForFacebookLogin: {
    color: '#232222',
    fontFamily: 'ProximaNova-Semibold',
    fontSize: 16,
    textAlign: 'left',
    marginVertical: 15,
  },
  facebookLoginButtonView: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'white',
    borderRadius: 25,
    elevation: 3,
    height: 50,
    alignSelf: 'center',
    flexDirection: 'row',
    width: 299.1,
  },
});
